-- =====================================================================
-- Facturación (servicios profesionales): facturas y cotizaciones + líneas.
-- Espejo de sales/sale_items. Convención: RLS FOR ALL TO authenticated con
-- (select auth.uid()), trigger set_user_id, índices en FKs.
-- =====================================================================
create table if not exists public.invoices (
  id              uuid primary key default gen_random_uuid(),
  invoice_number  bigint generated by default as identity,
  user_id         uuid not null default auth.uid() references auth.users(id) on delete cascade,
  customer_id     uuid references public.customers(id) on delete set null,
  type            text not null default 'factura',   -- factura | cotizacion
  status          text not null default 'pending',   -- pending | paid | cancelled
  issue_date      date not null default current_date,
  due_date        date,
  subtotal        numeric(12,2) not null default 0,
  discount_amount numeric(12,2) not null default 0,
  tax_rate        numeric(5,4)  not null default 0,
  tax_amount      numeric(12,2) not null default 0,
  total           numeric(12,2) not null default 0,
  notes           text,
  created_at      timestamptz not null default now()
);

create table if not exists public.invoice_items (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  invoice_id  uuid not null references public.invoices(id) on delete cascade,
  service_id  uuid references public.services(id) on delete set null,
  description text not null,
  quantity    numeric(12,2) not null default 1 check (quantity > 0),
  unit_price  numeric(12,2) not null default 0,
  line_total  numeric(12,2) not null default 0,
  created_at  timestamptz not null default now()
);

alter table public.invoices      enable row level security;
alter table public.invoice_items enable row level security;

create policy "Users manage own invoices" on public.invoices
  for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Users manage own invoice_items" on public.invoice_items
  for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create trigger set_invoices_user_id      before insert on public.invoices      for each row execute function public.set_user_id();
create trigger set_invoice_items_user_id before insert on public.invoice_items for each row execute function public.set_user_id();

create index if not exists invoices_user_id_idx          on public.invoices (user_id);
create index if not exists invoices_customer_id_idx       on public.invoices (customer_id);
create index if not exists invoices_created_at_idx        on public.invoices (created_at desc);
create index if not exists invoice_items_user_id_idx      on public.invoice_items (user_id);
create index if not exists invoice_items_invoice_id_idx   on public.invoice_items (invoice_id);
create index if not exists invoice_items_service_id_idx   on public.invoice_items (service_id);
