-- =====================================================================
-- Esquema de ventas + gastos + ajustes por cuenta.
-- Sigue las convenciones del proyecto: RLS FOR ALL TO authenticated con
-- (select auth.uid()), trigger set_user_id, e índices en toda FK.
-- =====================================================================

-- ---------- settings: configuración por cuenta (IVA configurable) ----------
create table if not exists public.settings (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  tax_rate    numeric(5,4) not null default 0.1600,  -- 0.1600 = 16% IVA
  currency    text not null default 'MXN',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id)
);

-- ---------- sales: cabecera de venta ----------
create table if not exists public.sales (
  id              uuid primary key default gen_random_uuid(),
  sale_number     bigint generated by default as identity,
  user_id         uuid not null references auth.users(id) on delete cascade,
  customer_id     uuid references public.customers(id) on delete set null,
  subtotal        numeric(12,2) not null default 0,
  discount_amount numeric(12,2) not null default 0,
  tax_rate        numeric(5,4)  not null default 0,   -- snapshot de la tasa aplicada
  tax_amount      numeric(12,2) not null default 0,
  total           numeric(12,2) not null default 0,
  payment_method  text not null default 'efectivo',   -- efectivo | tarjeta | transferencia
  status          text not null default 'completed',  -- completed | refunded | void
  created_at      timestamptz not null default now()
);

-- ---------- sale_items: líneas de venta (con snapshot del producto) ----------
create table if not exists public.sale_items (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  sale_id      uuid not null references public.sales(id) on delete cascade,
  product_id   uuid references public.products(id) on delete set null,
  product_name text not null,
  sku          text,
  unit_price   numeric(12,2) not null,
  quantity     integer not null check (quantity > 0),
  line_total   numeric(12,2) not null,
  created_at   timestamptz not null default now()
);

-- ---------- expenses: gastos para Finanzas ----------
create table if not exists public.expenses (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  description  text not null,
  category     text,
  amount       numeric(12,2) not null check (amount >= 0),
  expense_date date not null default current_date,
  created_at   timestamptz not null default now()
);

-- ---------- RLS ----------
alter table public.settings   enable row level security;
alter table public.sales      enable row level security;
alter table public.sale_items enable row level security;
alter table public.expenses   enable row level security;

create policy "Users manage own settings" on public.settings
  for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Users manage own sales" on public.sales
  for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Users manage own sale_items" on public.sale_items
  for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Users manage own expenses" on public.expenses
  for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- ---------- Triggers set_user_id (función ya endurecida en migración previa) ----------
create trigger set_settings_user_id   before insert on public.settings   for each row execute function public.set_user_id();
create trigger set_sales_user_id       before insert on public.sales       for each row execute function public.set_user_id();
create trigger set_sale_items_user_id  before insert on public.sale_items  for each row execute function public.set_user_id();
create trigger set_expenses_user_id    before insert on public.expenses    for each row execute function public.set_user_id();

-- ---------- updated_at automático en settings ----------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
revoke execute on function public.touch_updated_at() from public, anon, authenticated;

create trigger touch_settings_updated_at before update on public.settings
  for each row execute function public.touch_updated_at();

-- ---------- Índices en foreign keys ----------
create index if not exists sales_user_id_idx        on public.sales (user_id);
create index if not exists sales_customer_id_idx     on public.sales (customer_id);
create index if not exists sales_created_at_idx      on public.sales (created_at desc);
create index if not exists sale_items_user_id_idx    on public.sale_items (user_id);
create index if not exists sale_items_sale_id_idx    on public.sale_items (sale_id);
create index if not exists sale_items_product_id_idx on public.sale_items (product_id);
create index if not exists expenses_user_id_idx      on public.expenses (user_id);
create index if not exists expenses_date_idx         on public.expenses (expense_date desc);

-- =====================================================================
-- create_sale: registra una venta de forma transaccional.
--   - Calcula totales en el servidor (no confía en el cliente).
--   - Usa la tasa de IVA de la cuenta; 0 si el cliente es exento.
--   - Descuenta stock permitiendo valores negativos.
-- SECURITY INVOKER → respeta RLS (cada usuario solo toca sus filas).
-- p_items: jsonb [{"product_id":"uuid","quantity":2}, ...]
-- =====================================================================
create or replace function public.create_sale(
  p_customer_id    uuid,
  p_payment_method text,
  p_discount_amount numeric,
  p_items          jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_uid        uuid := (select auth.uid());
  v_sale_id    uuid;
  v_subtotal   numeric(12,2) := 0;
  v_discount   numeric(12,2) := coalesce(p_discount_amount, 0);
  v_tax_rate   numeric(5,4);
  v_tax_exempt boolean := false;
  v_taxable    numeric(12,2);
  v_tax_amount numeric(12,2);
  v_total      numeric(12,2);
  v_item       jsonb;
  v_product    public.products%rowtype;
  v_qty        integer;
begin
  if v_uid is null then
    raise exception 'No autenticado';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'La venta no tiene productos';
  end if;

  -- Tasa de IVA de la cuenta (16% por defecto si no hay ajustes)
  select s.tax_rate into v_tax_rate from public.settings s where s.user_id = v_uid;
  v_tax_rate := coalesce(v_tax_rate, 0.1600);

  -- Cliente exento → sin impuesto
  if p_customer_id is not null then
    select coalesce(c.tax_exempt, false) into v_tax_exempt
    from public.customers c where c.id = p_customer_id and c.user_id = v_uid;
    if v_tax_exempt then
      v_tax_rate := 0;
    end if;
  end if;

  insert into public.sales (user_id, customer_id, payment_method, discount_amount, tax_rate)
  values (v_uid, p_customer_id, coalesce(p_payment_method, 'efectivo'), v_discount, v_tax_rate)
  returning id into v_sale_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := (v_item->>'quantity')::integer;
    if v_qty is null or v_qty <= 0 then
      raise exception 'Cantidad inválida en la venta';
    end if;

    select * into v_product from public.products
    where id = (v_item->>'product_id')::uuid and user_id = v_uid;
    if not found then
      raise exception 'Producto no encontrado: %', v_item->>'product_id';
    end if;

    insert into public.sale_items
      (user_id, sale_id, product_id, product_name, sku, unit_price, quantity, line_total)
    values
      (v_uid, v_sale_id, v_product.id, v_product.name, v_product.sku,
       v_product.price, v_qty, v_product.price * v_qty);

    v_subtotal := v_subtotal + (v_product.price * v_qty);

    -- Descuenta stock (permite negativo)
    update public.products
      set stock_level = stock_level - v_qty, updated_at = now()
    where id = v_product.id and user_id = v_uid;
  end loop;

  v_taxable    := greatest(v_subtotal - v_discount, 0);
  v_tax_amount := round(v_taxable * v_tax_rate, 2);
  v_total      := v_taxable + v_tax_amount;

  update public.sales
    set subtotal = v_subtotal, tax_amount = v_tax_amount, total = v_total
  where id = v_sale_id and user_id = v_uid;

  return v_sale_id;
end;
$$;

revoke execute on function public.create_sale(uuid, text, numeric, jsonb) from public, anon;
grant   execute on function public.create_sale(uuid, text, numeric, jsonb) to authenticated;
